### PR TITLE
Added: Scanner effect

### PR DESCRIPTION
**Pull request by pathakshashank17**
I have decided to go with an effect of **Shadow + 55% Contrast** which looks close to scanned documents. Suggest changes if needed.

### CODE REVIEW

**Review by saurabhdaware — CHANGES_REQUESTED** [review]
This looks amazing! 

if I select 'scanner' effect and generate, it works great but when I select 'shadows' effect again, it still shows scanner effect in the output.

Also, What is exactly the need of `window.altEffect`? we can directly do `document.querySelector('#page-effects').value` no?

**Comment by pathakshashank17** [comment]
About the first issue, that was an unintentional bug.

About the second issue, the problem that I was facing was that if I did not change `document.querySelector('#page-effects').value` to `shadow`, all the page rulings vanished. It was because of that I had to use another variable to store the current effect and then revert back to it afterwards so that scanner effect could be applied.
[Check this image](https://user-images.githubusercontent.com/64695775/87042887-e32f9380-c211-11ea-9123-c51cb5fc8076.jpg)

It would be helpful if you would point out the exact code which draws ruling on the pages.

**Comment by pathakshashank17** [comment]
> This looks amazing!
> 
> if I select 'scanner' effect and generate, it works great but when I select 'shadows' effect again, it still shows scanner effect in the output.
> 
> Also, What is exactly the need of `window.altEffect`? we can directly do `document.querySelector('#page-effects').value` no?

Ok, I have made the changes. Suggest changes.

**Review by saurabhdaware — APPROVED** [review]
Looks perfect! Thank you so much, Shashank 🎉 This one of the coolest features we ever got! 

Do you have twitter account which I can tag in a tweet? or maybe anything that I can help you promote? 

Thanks!

**Comment by pathakshashank17** [comment]
> Looks perfect! Thank you so much, Shashank 🎉 This one of the coolest features we ever got!
> 
> Do you have twitter account which I can tag in a tweet? or maybe anything that I can help you promote?
> 
> Thanks!

Thanks a lot, I too learnt new things ! You can find me at [Twitter](https://twitter.com/pathkshashank17) or [Instagram](https://www.instagram.com/pathakshashank17/). Glad to be of help !

**Pull request merged**
