### PR TITLE
Feat: Draw Diagrams

### PR DESCRIPTION
**Pull request by saurabhdaware**
- Added Draw Diagrams feature to draw diagrams and add them to paper.
- HTML Made a little semantic (Idk why I mixed it with this branch but this is how it is now :c )
- Refactored to use modules.

### CODE REVIEW

**Review by saurabhdaware — COMMENTED** [review]
Thanks, Saurabh 🎉

**Comment by saurabhdaware** [comment]
Welcome, Saurabh 🌻

**Comment by saurabhdaware** [comment]
LGTM!

**Comment by saurabhdaware** [comment]
Thank you for merging, Saurabh.

**Comment by saurabhdaware** [comment]
Thank you for contributing, Saurabh 🐨

**Comment by saurabhdaware** [comment]
Dancing Pikachu GIF

**Comment by anuraghazra** [comment]
Lmao self reviewing?

**Comment by saurabhdaware** [comment]
Shh don't tell anyone 🙈

**Pull request merged**
