### PR TITLE
Added two scripts for converting text to handwriting using the command line

### PR DESCRIPTION
**Pull request by YourAKShaw**
One script converts a hard coded line of text to handwriting. Another takes a text file as input and converts all the lines to handwriting, each line being separated by a new-line character. Selenium web automation is used to achieve this. Furthermore, the chrome browser used has been made hidden, i.e., the script runs the tasks in the background, and hence gives the illusion of a feel of using the command line to get the desired result. Further improvements to the script are welcome, as only a few of the options have been scripted.

### CODE REVIEW

**Comment by ForceGT** [comment]
Bhai you the true CLI guy🙏

**Comment by saurabhdaware** [comment]
This is amazing @Ak-Shaw. It is a pretty cool way to do text-to-handwriting. I will give this a try this week. 

However, I think it is better to have it as a separate tool so maybe you can keep it in the fork since it won't be possible to explain and maintain it in this same repository.

But it is pretty cool and I'll definitely check it out and maybe contribute some day. Thanks for making it :D

**Comment by YourAKShaw** [comment]
@saurabhdaware should I then put this tool in a different repository of my own? I'll obviously give credits to your repository and your web app. I really think that people can make use of it.

In the different repository, I'll only keep the scripts, and give guidelines on how to use it.

**Comment by saurabhdaware** [comment]
yes yes that totally makes sense!

**Comment by YourAKShaw** [comment]
https://github.com/Ak-Shaw/text-to-handwriting-script

**Pull request closed without merging**
