### PR TITLE
Added new handwriting fonts for simple use.

### PR DESCRIPTION
**Pull request by arshsisodiya**
i added 30+ new handwriting fonts, people can choose from different fonts, now they dont have to search on web for handwriting fonts, searching perfect handwriting fonts on web is hactic task for some people,
they can simply select from the "handwriting fonts section itself",

### CODE REVIEW

**Comment by saurabhdaware** [comment]
These all look amazing @arshsisodiya. But May I know where did you get these fonts from? There may be licenses to these fonts which I would have to read before adding them to website.

**Comment by arshsisodiya** [comment]
> 
> 
> These all look amazing @arshsisodiya. But May I know where did you get these fonts from? There may be licenses to these fonts which I would have to read before adding them to website.


first of all sorry to reply too late,

 i downloaded all these fonts from https://www.quantumenterprises.co.uk/handwriting-fonts/fontvault.htm i hope there is no big issue related to license.

**Review by saurabhdaware — APPROVED** [review]
~Looks good Arsh! Thank you so much for contributing! I will add some attribution and credits to the website and merge it with the master.~

**Comment by saurabhdaware** [comment]
I just checked their license and they have mentioned-
> In the context of using our handwriting fonts, commercial use is the 'use of a font by an individual or business directly or indirectly for financial gain'.

~ [Handwriting Fonts Commercial License](https://www.quantumenterprises.co.uk/handwriting-fonts/fontpayment.htm)

Though text-to-handwriting is not a direct commercial software, It still can be counted as `indirect financial gain` due to the donations and sponsors so I don't think so it is ethical to go with the fonts.

**Pull request closed without merging**
