### PR TITLE
New Featute : Dark mode

### LINKED ISSUE #50: Dark Mode Please?
**Is your feature request related to a problem? Please describe.**
My eyes are burning xD

**Describe the solution you'd like**
A well developed dark mode with #000 and not #999

### PR DESCRIPTION
**Pull request by harshilparmar**
I have tried #50.

Please let me know is it Ok or not? Correct me if I am wrong!! 

EDIT:
fixes #50

### CODE REVIEW

**Comment by saurabhdaware** [comment]
Thank you, Harshil! I haven't checked properly yet but can wo do something for this:
Screenshot of dark mode toggle that shows it is being overlapped by github icon
The toggle is not clickable because of that github icon

Maybe we can bring the toggle a little down (along with the content) so adding top padding to that main container should do the job.


Also maybe we can make the dark color a little darker and turn inputs dark as well. 

You can refer to this CSS:
https://github.com/abelljs/abell-starter-minima/blob/main/theme/styles/inlined/global.css.js

**Comment by saurabhdaware** [comment]
Oh and off-topic of this PR but your profile is not showing up in the commits and if you send PRs to repositories without that, even after getting PR merged your name won't show up in the contributors. 

I guess its because email and name in your terminal is not configured or the email in your GitHub account is different from the one set in terminal.

Maybe try running git config --global user.email and see what email id it outputs and then set/add that email id in GitHub from https://github.com/settings/emails

**Comment by harshilparmar** [comment]
> 
> 
> Thank you, Harshil! I haven't checked properly yet but can wo do something for this:
> Screenshot of dark mode toggle that shows it is being overlapped by github icon
> The toggle is not clickable because of that github icon
> 
> Maybe we can bring the toggle a little down (along with the content) so adding top padding to that main container should do the job.
> 
> Also maybe we can make the dark color a little darker and turn inputs dark as well.
> 
> You can refer to this CSS:
> https://github.com/abelljs/abell-starter-minima/blob/main/theme/styles/inlined/global.css.js

Ohh Thanks,I will change that.

**Review by harshilparmar — COMMENTED** [review]
Is this right brother @saurabhdaware !!

**Review by saurabhdaware — APPROVED** [review]
Yes! Looking great! Thank you @harshilparmar

**Comment by harshilparmar** [comment]
> 
> 
> Yes! Looking great! Thank you @harshilparmar

Thanks bro!!! I want to ask some questions to you.Can I mail that or Can I ask here??

**Comment by saurabhdaware** [comment]
Wherever you're comfortable asking

My mail is: saurabhdaware99@gmail.com

**Pull request merged**
