### PR TITLE
Fixes Page Scroll Issue

### LINKED ISSUE #81: Text from Margins is printed on every page.
**Describe the bug**
When we generate multiple pages, the text from margin is printed on all the pages.

**To Reproduce**
1. Add text to margin
2. Add more text to paper so that it will have to generate multiple pages
3. Click Generate Image

**Expected behavior**
It is expected that the text from margin is only printed on first page.

**Screenshots**
Picture of 3 gernated images which have same margin text

### LINKED ISSUE #82: Left Margin doesn't scale well with body content
**Describe the bug**
Since Left margin element is an independent html component from the body content it doesn't scale as the body content size is increased beyond one page as indicated by the pink margin which stops at the end of first page in preview. 
Also when the size of left margin is increased beyond one page the scroll position of left margin can be different from the scroll position of body content which leads to confusion while writing as well as when pdf generated depends upon the scroll position of left margin.

**To Reproduce**
1. Go to the project site
2. Add content to page such that it goes beyond one A4 page
3. Now Add content to left margin such that its size increase beyond one page
4. Then scroll the left margin a little down such that the sroll bar is somewhere in the middle position
5. Generate PDF

**Expected behavior**
If the current preview design is maintained as it is then the left margin element should increase its size as the body content size increases making the pink border extend to the next page in preview. Also, while generating pdf the scroll position of left margin shouldn't affect the final result.
If the current design is allowed to change then as per me whenever the page size increase beyond A4 the current page should not increase its size rather a similar A4 size page should be concatenated to the existing A4 pages and control should be transfer to the next page.

**Screenshots**
1. Pink border of left margin doesn't scale
image

2. Scroll position dependency
Preview:
image
PDF generated:

image 
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Mozilla Firefox
 - Version 79.0 (64bit)

**Additional context**
Related Issue: https://github.com/saurabhdaware/text-to-handwriting/issues/81

**Query**
why we are adding a div element inside left margin container whenever a carriage return is pressed to enter the next line? Can't we just add the content in a single div element as done with body content?

### PR DESCRIPTION
**Pull request by CaptainDredge**
Fixes #81 Fixes #82 

In this PR I've tried to solve issue #81 and #82 by making the whole layout of pages discrete rather than continuous ones. It has several advantages in terms of performance as well as user interaction.

### CODE REVIEW

**Comment by saurabhdaware** [comment]
Thank you for the PR @CaptainDredge. I haven't checked PR properly but we can't paste content inside page. It is throwing some error in console. Can you check?

Also, is there any reason why it is using jQuery and not JavaScript. It is better to avoid additional dependencies as it will make code complicated to maintain. Can it be done without jQuery?

**Comment by CaptainDredge** [comment]
@saurabhdaware I've corrected the paste event handler. Also, Jquery is necessary for event delegation in dynamically added pages.  There's neither an easy nor an elegant solution of this in pure javascript.

**Comment by CaptainDredge** [comment]
@saurabhdaware  Have you looked into the PR now?

**Comment by saurabhdaware** [comment]
Hi there, I am on a break right now so I will try to check it by the next week. I hope it is fine with you. Thanks!

**Comment by saurabhdaware** [comment]
Hi, I just checked in the preview. It is not working when we have text larger than the area. Normally it is suppose to generate multiple images when a user pastes large text in the textarea.

**Comment by CaptainDredge** [comment]
No according to updated functionality user can paste as much text as he wants but page will contain only the text it can accommodate on one page. Then you've to add another page to paste the remaining text. And that's how even actual pages in notebook works. Adding the functionality of accommodating all the text and moving it to the next pages according to current status of page capacity itself is a pretty complicated task and that'll essentially make it like MS word.

**Comment by saurabhdaware** [comment]
No, I meant pasting large text at once. It was one of the reasons to have a scrollbar so that they can paste in one box. There were lots of people initially who wanted a way to generate multiple images in a single paste so the usecase is too common to ignore

**Comment by CaptainDredge** [comment]
@saurabhdaware  Added that functionality although I had to do a lot of thinking behind implementing it 😅 
You can now paste large text and it'll generate new pages accordingly. Also, when typing when the current page gets filled it'll generate the next page automatically. If the pasted content is too large it does have some performance implications associated with it.

**Comment by saurabhdaware** [comment]
This looks amazing! 

Few things are not working as expected:
https://res.cloudinary.com/saurabhdaware/video/upload/v1598336022/photos/2020-08-25_11-40-06.mp4

- While typing if I press the spacebar, it considers it as a line break and takes the cursor to next line
- When I try to CTRL + C to copy the selected section, it removes the selection
- Backspace is not working after selecting text content.

Let me know if it is possible to fix this otherwise maybe I can take this code to separate branch and see if I can do something. 

Thanks and not sure if adding page below was intended but it actually looks great! maybe we can have a scrollbar like we had before but have multiple pages in the scroll instead a single section. That would look great

**Comment by CaptainDredge** [comment]
I think its happening because of the event handlers attached to key down. But the keys pressed here like `^C` and `backspace` are not meant to trigger those callbacks attached to those handlers.  The first issue where spacebar is adding line breaks is not there in Google chrome which I use but its there in Firefox. I think there's some cross-browser compatibility issue in some function used in code which seems tough to figure out. You can definitely take the code to a separate branch to figure things out especially the first issue.

**Comment by CaptainDredge** [comment]
@saurabhdaware have checked on the first issue? I had already resolved the other two

**Comment by saurabhdaware** [comment]
not yet. I'll merge the PR in separate branch and will check what I can do. Thank youu!

**Review by saurabhdaware — APPROVED** [review]
Thank you so much! I'll see what we can do. Thank you.

**Comment by CaptainDredge** [comment]
So will I be added to the contributor list or not?

**Comment by saurabhdaware** [comment]
Yes you will be added to contributor list. The list on the website comes from GitHub API so the name will be reflect there after I merge this new branch into master. I will have to make some changes before that.

**Comment by prafulla-codes** [comment]
@saurabhdaware can you let me know what are the issues here?

**Pull request merged**
