### PR TITLE
PDF generator

### PR DESCRIPTION
**Pull request by Saurabh-Singh-00**

### CODE REVIEW

**Comment by Saurabh-Singh-00** [comment]
The newly generated image is not reflected in PDF as of now.

**Comment by saurabhdaware** [comment]
looks good, I'll check tomorrow. Thank you!

**Comment by saurabhdaware** [comment]
ahh didn't mean to close I pushed to wrong branch :cry: I fixed the issue though it was because the alias name was not dynamic
```js
 doc.addImage(imgs[i], 'JPEG', 25, 50, width - 50, (height - 80), "image-"+i);
```
adding `"image-"+i` solved it.

Wait I'll try to figure out if there is any way to solve this git issue :sob:

**Comment by saurabhdaware** [comment]
Thanks @Saurabh-Singh-00 I'll check in the morning 🎉✨

**Review by saurabhdaware — APPROVED** [review]
Thank you so much @Saurabh-Singh-00 🎉 This is the coolest feature everrrr!! Getting it merged :dancers:

**Pull request merged**
